### ISSUE TITLE
Apply activeClassName to selector columns across site

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#127]
## What's the expected behavior?

When a selector column is active, the column should remain coloured while that column is active.

## What page/new page is this for?

- /residents
- /residents/`:uid`
- /search

## File(s) involved, include line(s) if known

**Sample React Code**

```js
<Link activeClassName="Link--is-active" to="/work">
  Work
</Link>
```

**Sample SCSS Code**

```scss
a {
    color: currentColor;
    text-decoration: none;
    border-bottom: 3px solid transparent;
    font-weight: 600;
    font-size: 0.95em;
    height: 100%;
    padding-bottom: 1.25em;
    padding-top: 0.25em;
    display: block;
    position: relative;

    &:after {
      position: absolute;
      content: "";
      bottom: 0;
      width: 18px;
      height: 3px;
      background: transparent;
      bottom: -3px;
      right: 50%;
      margin-right: -9px;
      transition: 100ms ease-in-out background;
    }

    &:hover {
      &:after {
        background: ${colors.blue500};
        transition: 100ms ease-in-out background;
      }
    }

    &.Link--is-active {
      &:after {
        background: ${colors.blue500};
        transition: 100ms ease-in-out background;
      }
    }
  }
```

**Column Selector Buttons - Resident.js**
https://github.com/SLB-Pizza/radio-pizza/blob/0f105b0d6c472736262d1925c87341afb8f93c17/src/templates/Resident.js#L48-L59
